/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeHomeRouteImport } from './routes/(home)/_home'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as homeHomeIndexRouteImport } from './routes/(home)/_home/index'
import { Route as homeHomeCoursesRouteImport } from './routes/(home)/_home/courses'
import { Route as homeHomeCourseCourseRouteImport } from './routes/(home)/_home/course/$course'
import { Route as codeCourseCourseLearnRouteImport } from './routes/(code)/course/$course/learn'
import { Route as codeCourseCourseLearnIndexRouteImport } from './routes/(code)/course/$course/learn/index'
import { Route as codeCourseCourseLearnLessonRouteImport } from './routes/(code)/course/$course/learn/$lesson'

const homeHomeRoute = homeHomeRouteImport.update({
  id: '/(home)/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const homeHomeIndexRoute = homeHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeHomeRoute,
} as any)
const homeHomeCoursesRoute = homeHomeCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => homeHomeRoute,
} as any)
const homeHomeCourseCourseRoute = homeHomeCourseCourseRouteImport.update({
  id: '/course/$course',
  path: '/course/$course',
  getParentRoute: () => homeHomeRoute,
} as any)
const codeCourseCourseLearnRoute = codeCourseCourseLearnRouteImport.update({
  id: '/(code)/course/$course/learn',
  path: '/course/$course/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const codeCourseCourseLearnIndexRoute =
  codeCourseCourseLearnIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => codeCourseCourseLearnRoute,
  } as any)
const codeCourseCourseLearnLessonRoute =
  codeCourseCourseLearnLessonRouteImport.update({
    id: '/$lesson',
    path: '/$lesson',
    getParentRoute: () => codeCourseCourseLearnRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/courses': typeof homeHomeCoursesRoute
  '/': typeof homeHomeIndexRoute
  '/course/$course/learn': typeof codeCourseCourseLearnRouteWithChildren
  '/course/$course': typeof homeHomeCourseCourseRoute
  '/course/$course/learn/$lesson': typeof codeCourseCourseLearnLessonRoute
  '/course/$course/learn/': typeof codeCourseCourseLearnIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/courses': typeof homeHomeCoursesRoute
  '/': typeof homeHomeIndexRoute
  '/course/$course': typeof homeHomeCourseCourseRoute
  '/course/$course/learn/$lesson': typeof codeCourseCourseLearnLessonRoute
  '/course/$course/learn': typeof codeCourseCourseLearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(home)/_home': typeof homeHomeRouteWithChildren
  '/(home)/_home/courses': typeof homeHomeCoursesRoute
  '/(home)/_home/': typeof homeHomeIndexRoute
  '/(code)/course/$course/learn': typeof codeCourseCourseLearnRouteWithChildren
  '/(home)/_home/course/$course': typeof homeHomeCourseCourseRoute
  '/(code)/course/$course/learn/$lesson': typeof codeCourseCourseLearnLessonRoute
  '/(code)/course/$course/learn/': typeof codeCourseCourseLearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/courses'
    | '/'
    | '/course/$course/learn'
    | '/course/$course'
    | '/course/$course/learn/$lesson'
    | '/course/$course/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/courses'
    | '/'
    | '/course/$course'
    | '/course/$course/learn/$lesson'
    | '/course/$course/learn'
  id:
    | '__root__'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(home)/_home'
    | '/(home)/_home/courses'
    | '/(home)/_home/'
    | '/(code)/course/$course/learn'
    | '/(home)/_home/course/$course'
    | '/(code)/course/$course/learn/$lesson'
    | '/(code)/course/$course/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  homeHomeRoute: typeof homeHomeRouteWithChildren
  codeCourseCourseLearnRoute: typeof codeCourseCourseLearnRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/_home': {
      id: '/(home)/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_home/': {
      id: '/(home)/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeHomeIndexRouteImport
      parentRoute: typeof homeHomeRoute
    }
    '/(home)/_home/courses': {
      id: '/(home)/_home/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof homeHomeCoursesRouteImport
      parentRoute: typeof homeHomeRoute
    }
    '/(home)/_home/course/$course': {
      id: '/(home)/_home/course/$course'
      path: '/course/$course'
      fullPath: '/course/$course'
      preLoaderRoute: typeof homeHomeCourseCourseRouteImport
      parentRoute: typeof homeHomeRoute
    }
    '/(code)/course/$course/learn': {
      id: '/(code)/course/$course/learn'
      path: '/course/$course/learn'
      fullPath: '/course/$course/learn'
      preLoaderRoute: typeof codeCourseCourseLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(code)/course/$course/learn/': {
      id: '/(code)/course/$course/learn/'
      path: '/'
      fullPath: '/course/$course/learn/'
      preLoaderRoute: typeof codeCourseCourseLearnIndexRouteImport
      parentRoute: typeof codeCourseCourseLearnRoute
    }
    '/(code)/course/$course/learn/$lesson': {
      id: '/(code)/course/$course/learn/$lesson'
      path: '/$lesson'
      fullPath: '/course/$course/learn/$lesson'
      preLoaderRoute: typeof codeCourseCourseLearnLessonRouteImport
      parentRoute: typeof codeCourseCourseLearnRoute
    }
  }
}

interface homeHomeRouteChildren {
  homeHomeCoursesRoute: typeof homeHomeCoursesRoute
  homeHomeIndexRoute: typeof homeHomeIndexRoute
  homeHomeCourseCourseRoute: typeof homeHomeCourseCourseRoute
}

const homeHomeRouteChildren: homeHomeRouteChildren = {
  homeHomeCoursesRoute: homeHomeCoursesRoute,
  homeHomeIndexRoute: homeHomeIndexRoute,
  homeHomeCourseCourseRoute: homeHomeCourseCourseRoute,
}

const homeHomeRouteWithChildren = homeHomeRoute._addFileChildren(
  homeHomeRouteChildren,
)

interface codeCourseCourseLearnRouteChildren {
  codeCourseCourseLearnLessonRoute: typeof codeCourseCourseLearnLessonRoute
  codeCourseCourseLearnIndexRoute: typeof codeCourseCourseLearnIndexRoute
}

const codeCourseCourseLearnRouteChildren: codeCourseCourseLearnRouteChildren = {
  codeCourseCourseLearnLessonRoute: codeCourseCourseLearnLessonRoute,
  codeCourseCourseLearnIndexRoute: codeCourseCourseLearnIndexRoute,
}

const codeCourseCourseLearnRouteWithChildren =
  codeCourseCourseLearnRoute._addFileChildren(
    codeCourseCourseLearnRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  homeHomeRoute: homeHomeRouteWithChildren,
  codeCourseCourseLearnRoute: codeCourseCourseLearnRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
