/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeHomeRouteImport } from './routes/(home)/_home'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as homeHomeIndexRouteImport } from './routes/(home)/_home/index'
import { Route as homeHomeCoursesRouteImport } from './routes/(home)/_home/courses'

const homeHomeRoute = homeHomeRouteImport.update({
  id: '/(home)/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const homeHomeIndexRoute = homeHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeHomeRoute,
} as any)
const homeHomeCoursesRoute = homeHomeCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => homeHomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/courses': typeof homeHomeCoursesRoute
  '/': typeof homeHomeIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/courses': typeof homeHomeCoursesRoute
  '/': typeof homeHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(home)/_home': typeof homeHomeRouteWithChildren
  '/(home)/_home/courses': typeof homeHomeCoursesRoute
  '/(home)/_home/': typeof homeHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/sign-up' | '/courses' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/sign-up' | '/courses' | '/'
  id:
    | '__root__'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(home)/_home'
    | '/(home)/_home/courses'
    | '/(home)/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  homeHomeRoute: typeof homeHomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/_home': {
      id: '/(home)/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_home/': {
      id: '/(home)/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeHomeIndexRouteImport
      parentRoute: typeof homeHomeRoute
    }
    '/(home)/_home/courses': {
      id: '/(home)/_home/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof homeHomeCoursesRouteImport
      parentRoute: typeof homeHomeRoute
    }
  }
}

interface homeHomeRouteChildren {
  homeHomeCoursesRoute: typeof homeHomeCoursesRoute
  homeHomeIndexRoute: typeof homeHomeIndexRoute
}

const homeHomeRouteChildren: homeHomeRouteChildren = {
  homeHomeCoursesRoute: homeHomeCoursesRoute,
  homeHomeIndexRoute: homeHomeIndexRoute,
}

const homeHomeRouteWithChildren = homeHomeRoute._addFileChildren(
  homeHomeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  homeHomeRoute: homeHomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
